### ISSUE TITLE
Display a Buffer Array of pixels in 2D OpenGL 2.0 ES

### ISSUE THREAD

**Issue by AhmedX6** [regar007/ShapesInOpenGLES2.0#1]
I want to display a **fullscreen** texture in **2D**.
I'm implementing a mirror protocol.
The client sends me a buffer object of pixels (1920x1080) and I just grab it and I just want to display it in my
Android Screen.

Here is my buffer how I construct it : 
`static IntBuffer mybuffer = BufferUtils.createIntBuffer(8300000);
byteBuffer.put(256) // ALPHA
 byteBuffer.put(150) // RED
 byteBuffer.put(152) // GREEN
 byteBuffer.put(23) // BLUE
 byteBuffer.put(152) // ALPHA
 ... etc etc`

Here is my renderer : 
`private class Renderer implements GLSurfaceView.Renderer {
        private int[] textures = new int[1];
        private int[] vertexes = new int[1];

        public void onDrawFrame(GL10 gl) {
            GLES20.glClearColor(0.1f, 0.1f, 1.0f, 1.0f);
            GLES20.glClear(GLES20.GL_DEPTH_BUFFER_BIT | GLES20.GL_COLOR_BUFFER_BIT);
            //step();
            GLES20.glGenTextures(1, vertexes, 0);
            GLES20.glBindTexture(GL10.GL_VERTEX_ARRAY, vertexes[0]);

            GLES20.glGenTextures(1, textures, 0);
            GLES20.glBindTexture(GL10.GL_TEXTURE_2D, textures[0]);

            GLES20.glTexImage2D(GL10.GL_TEXTURE_2D, 0, GL10.GL_RGBA, 1920, 1080, 0, GL10.GL_RGBA, GL10.GL_UNSIGNED_BYTE, mybuffer);

            //Here I should draw but don't know how to do it.
        }

        public void onSurfaceChanged(GL10 gl, int width, int height) {
            init(width, height);
        }

        public void onSurfaceCreated(GL10 gl, EGLConfig config) {
        }
    }`
I know that the order to draw something in therory is :  load the texture, setup a vertex and fragment shader, create a vertex buffer for a fullscreen quad and a create vertex arrays. Then go about binding it all and issue a draw call.
Can I have some help about that ?

Thank you !

**Comment by regar007** [comment]
Sorry for the late reply. In case you are still trying.

Since you want to use buffer object of pixels, there are two ways to go about it.
1. Create a height map of that resolution and apply these pixel buffer to color attribute.
 link for [heightmap](http://www.learnopengles.com/tag/height-maps/)

2. Convert somehow pixels to texture and bind it to a texture and apply it Quad using UV coords. 
link for conversion [pixel to image](http://stackoverflow.com/questions/9396159/how-do-i-create-a-bufferedimage-from-array-containing-pixels)

I think I can help you with the first approach, since I have worked on this a little. I have the working code for full screen height map and then you work with color attribute to get it working.

Let me know if you want to proceed with this.
